# Changelog

## 03/03/2025
- Start on kmeans
- Add functionality to view dataset information

View dataset info: head, duplicates, column info, numerical stats, any null values?

In [3]:
import pandas as pd
import numpy as np

# Read the dataset with proper delimiter
df = pd.read_csv('e-shop-clothing-2008.csv', delimiter=';')

# Basic information about the dataset
print(f"Dataset Shape: {df.shape} (rows, columns)")
print(f"Dataset Size: {df.size} elements")
print(f"Memory Usage: {df.memory_usage().sum() / 1024**2:.2f} MB")

# Display first rows
print("\nFirst 5 rows:")
print(df.head())

# Check for duplicates
duplicates = df.duplicated().sum()
print(f"\nDuplicates: {duplicates} rows")

# Column information
print("\nColumn Information:")
column_info = pd.DataFrame({
    'Data Type': df.dtypes,
    'Non-Null Count': df.count(),
    'Null Count': df.isnull().sum(),
    'Unique Values': [df[col].nunique() for col in df.columns]
})
print(column_info)

# Basic statistics
print("\nNumerical Statistics:")
print(df.describe())

# Check for missing values
missing_values = df.isnull().sum()
if missing_values.sum() > 0:
    print("\nMissing Values:")
    print(missing_values[missing_values > 0])

Dataset Shape: (165474, 14) (rows, columns)
Dataset Size: 2316636 elements
Memory Usage: 17.67 MB

First 5 rows:
   year  month  day  order  country  session ID  page 1 (main category)  \
0  2008      4    1      1       29           1                       1
1  2008      4    1      2       29           1                       1
2  2008      4    1      3       29           1                       2
3  2008      4    1      4       29           1                       2
4  2008      4    1      5       29           1                       2

  page 2 (clothing model)  colour  location  model photography  price  \
0                     A13       1         5                  1     28
1                     A16       1         6                  1     33
2                      B4      10         2                  1     52
3                     B17       6         6                  2     38
4                      B8       4         3                  2     52

   price 2  page
0        2     1
1        2     1
2        1     1
3        2     1
4        1     1

Duplicates: 0 rows

Column Information:
                        Data Type  Non-Null Count  Null Count  Unique Values
year                        int64          165474           0              1
month                       int64          165474           0              5
day                         int64          165474           0             31
order                       int64          165474           0            195
country                     int64          165474           0             47
session ID                  int64          165474           0          24026
page 1 (main category)      int64          165474           0              4
page 2 (clothing model)    object          165474           0            217
colour                      int64          165474           0             14
location                    int64          165474           0              6
model photography           int64          165474           0              2
price                       int64          165474           0             20
price 2                     int64          165474           0              2
page                        int64          165474           0              5

Numerical Statistics:
           year          month            day          order        country  \
count  165474.0  165474.000000  165474.000000  165474.000000  165474.000000
mean     2008.0       5.585887      14.524554       9.817476      26.952621
std         0.0       1.328160       8.830374      13.478411       7.150691
min      2008.0       4.000000       1.000000       1.000000       1.000000
25%      2008.0       4.000000       7.000000       2.000000      29.000000
50%      2008.0       5.000000      14.000000       6.000000      29.000000
75%      2008.0       7.000000      22.000000      12.000000      29.000000
max      2008.0       8.000000      31.000000     195.000000      47.000000

          session ID  page 1 (main category)         colour       location  \
count  165474.000000           165474.000000  165474.000000  165474.000000
mean    12058.417056                2.400842       6.227655       3.258198
std      7008.418903                1.144420       4.235606       1.713206
min         1.000000                1.000000       1.000000       1.000000
25%      5931.000000                1.000000       3.000000       2.000000
50%     11967.500000                2.000000       4.000000       3.000000
75%     18219.000000                3.000000       9.000000       5.000000
max     24026.000000                4.000000      14.000000       6.000000

       model photography          price        price 2           page
count      165474.000000  165474.000000  165474.000000  165474.000000
mean            1.260071      43.802507       1.488167       1.710166
std             0.438674      12.548131       0.499861       0.982412
min             1.000000      18.000000       1.000000       1.000000
25%             1.000000      33.000000       1.000000       1.000000
50%             1.000000      43.000000       1.000000       1.000000
75%             2.000000      52.000000       2.000000       2.000000
max             2.000000      82.000000       2.000000       5.000000